<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Email;

/**
 * EmailRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEmailsToSend()
    {
        $query = $this->createQueryBuilder('t0')
            ->where('t0.status != :status OR t0.status IS NULL')
            ->setParameter('status', Email::STATUS_SENT)
            ->orderBy('t0.priority', 'DESC')
            ->getQuery();
        try {
            return $items = $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return;
        }
    }
}
