# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mailer:
       class: AppBundle\Service\Mailer
       arguments: ['@logger', '@mailer']
    app.serializer:
       class: AppBundle\Service\Serializer
       arguments: []
